# This file is used by the iosevka font build system
#
# From the Iosevka repo root, build like this. the jCmd sets
# the number of CPUs and thus also a limit on the memory as 
# it can take a long time (like an hour or more) to build,
# and without a limit it might consume all system resources.
#
# The Fancy versions include coding ligatures
# The Mail versions are stripped down for HTML email embedding
# (NOTE: Two colons after the format)

# npm run build -- --jCmd=8 woff2::VanadiumSans
# npm run build -- --jCmd=8 woff2::VanadiumSansFancy
# npm run build -- --jCmd=8 woff2::VanadiumMono
# npm run build -- --jCmd=8 woff2::VanadiumMonoFancy
# npm run build -- --jCmd=8 woff2-unhinted::VanadiumSansMail
# npm run build -- --jCmd=8 woff2-unhinted::VanadiumMonoMail

########################
# Vanadium Sans
########################

[buildPlans.VanadiumSans]
family = "Vanadium Sans"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.VanadiumSans.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
k = "symmetric-connected-serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.VanadiumSans.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.VanadiumSans.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.VanadiumSans.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.VanadiumSans.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.VanadiumSans.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.VanadiumSans.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.VanadiumSans.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Vanadium Sans Fancy
########################

[buildPlans.VanadiumSansFancy]
family = "Vanadium Sans Fancy"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.VanadiumSansFancy.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
k = "symmetric-connected-serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.VanadiumSansFancy.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.VanadiumSansFancy.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.VanadiumSansFancy.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.VanadiumSansFancy.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.VanadiumSansFancy.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.VanadiumSansFancy.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.VanadiumSansFancy.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Vanadium Mono
########################

[buildPlans.VanadiumMono]
family = "Vanadium Mono"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.VanadiumMono.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
k = "symmetric-connected-serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.VanadiumMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.VanadiumMono.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.VanadiumMono.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.VanadiumMono.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.VanadiumMono.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.VanadiumMono.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.VanadiumMono.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Vanadium Mono Fancy
########################

[buildPlans.VanadiumMonoFancy]
family = "Vanadium Mono Fancy"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.VanadiumMonoFancy.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
k = "symmetric-connected-serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.VanadiumMonoFancy.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.VanadiumMonoFancy.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.VanadiumMonoFancy.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.VanadiumMonoFancy.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.VanadiumMonoFancy.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.VanadiumMonoFancy.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.VanadiumMonoFancy.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Vanadium Sans Mail
########################

[buildPlans.VanadiumSansMail]
family = "Vanadium Sans Mail"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.VanadiumSansMail.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
k = "symmetric-connected-serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"
[buildPlans.VanadiumSansMail.variations]
enabled = true

[buildPlans.VanadiumSansMail.variations.axes.wght]
min = 400
max = 700
default = 400

[buildPlans.VanadiumSansMail.subset]
include.ranges = [
  [32, 126],   # Basic ASCII printable
  [160, 255],  # Latin-1 Supplement
]

########################
# Vanadium Mono Mail
########################

[buildPlans.VanadiumMonoMail]
family = "Vanadium Mono Mail"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.VanadiumMonoMail.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
k = "symmetric-connected-serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.VanadiumMonoMail.variations]
enabled = true

[buildPlans.VanadiumMonoMail.variations.axes.wght]
min = 400
max = 700
default = 400
# Add these to restrict instances
[buildPlans.VanadiumMonoMail.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.VanadiumMonoMail.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.VanadiumMonoMail.widths.Normal]
shape = 500   # Or whatever your normal unit width is (default is usually fine)
menu = 5
css = "normal"

[buildPlans.VanadiumMonoMail.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.VanadiumMonoMail.subset]
include.ranges = [
  [32, 126],   # Basic ASCII printable
  [160, 255],  # Latin-1 Supplement
]
