# This file is used by the iosevka font build system
#
# From the Iosevka repo root, build like this. the jCmd sets
# the number of CPUs and thus also a limit on the memory as 
# it can take a long time (like an hour or more) to build,
# and without a limit it might consume all system resources.
#
# The Fancy versions include coding ligatures
# The Mail versions are stripped down for HTML email embedding
# (NOTE: Two colons after the format)

# npm run build -- --jCmd=8 woff2::AcuranzoSans
# npm run build -- --jCmd=8 woff2::AcuranzoSansFancy
# npm run build -- --jCmd=8 woff2::AcuranzoMono
# npm run build -- --jCmd=8 woff2::AcuranzoMonoFancy
# npm run build -- --jCmd=8 woff2-unhinted::AcuranzoSansMail
# npm run build -- --jCmd=8 woff2-unhinted::AcuranzoMonoMail

########################
# Acuranzo Sans
########################

[buildPlans.AcuranzoSans]
family = "Acuranzo Sans Fancy"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.AcuranzoSans.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.AcuranzoSans.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.AcuranzoSans.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.AcuranzoSans.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.AcuranzoSans.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.AcuranzoSans.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.AcuranzoSans.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.AcuranzoSans.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Acuranzo Sans Fancy
########################

[buildPlans.AcuranzoSansFancy]
family = "Acuranzo Sans Fancy"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.AcuranzoSansFancy.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.AcuranzoSansFancy.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.AcuranzoSansFancy.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.AcuranzoSansFancy.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.AcuranzoSansFancy.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.AcuranzoSansFancy.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.AcuranzoSansFancy.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.AcuranzoSansFancy.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Acuranzo Mono
########################

[buildPlans.AcuranzoMono]
family = "Acuranzo Mono"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.AcuranzoMono.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.AcuranzoMono.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.AcuranzoMono.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.AcuranzoMono.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.AcuranzoMono.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.AcuranzoMono.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.AcuranzoMono.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.AcuranzoMono.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Acuranzo Mono Fancy
########################

[buildPlans.AcuranzoMonoFancy]
family = "Acuranzo Mono Fancy"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.AcuranzoMonoFancy.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.AcuranzoMonoFancy.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.AcuranzoMonoFancy.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.AcuranzoMonoFancy.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.AcuranzoMonoFancy.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.AcuranzoMonoFancy.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.AcuranzoMonoFancy.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.AcuranzoMonoFancy.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"

########################
# Acuranzo Sans Mail
########################

[buildPlans.AcuranzoSansMail]
family = "Acuranzo Sans Mail"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.AcuranzoSansMail.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"
[buildPlans.AcuranzoSansMail.variations]
enabled = true

[buildPlans.AcuranzoSansMail.variations.axes.wght]
min = 400
max = 700
default = 400

[buildPlans.AcuranzoSansMail.subset]
include.ranges = [
  [32, 126],   # Basic ASCII printable
  [160, 255],  # Latin-1 Supplement
]

########################
# Acuranzo Mono Mail
########################

[buildPlans.AcuranzoMonoMail]
family = "Acuranzo Mono Mail"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.AcuranzoMonoMail.variants.design]
one = "no-base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-flat-serifless"
six = "open-contour"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-m = "flat-bottom-serifless"
capital-q = "crossing"
capital-r = "straight-serifless"
capital-w = "straight-flat-top-serifless"
a = "single-storey-earless-corner-serifless"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-rounded"
i = "flat-tailed"
j = "serifless"
l = "flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook-asymmetric"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
asterisk = "hex-low"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "straight"
guillemet = "curly"
number-sign = "upright-tall"
ampersand = "closed"
dollar = "slanted-through"
percent = "rings-continuous-slash"
question = "corner-flat-hooked"

[buildPlans.AcuranzoMonoMail.variations]
enabled = true

[buildPlans.AcuranzoMonoMail.variations.axes.wght]
min = 400
max = 700
default = 400
# Add these to restrict instances
[buildPlans.AcuranzoMonoMail.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.AcuranzoMonoMail.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.AcuranzoMonoMail.widths.Normal]
shape = 500   # Or whatever your normal unit width is (default is usually fine)
menu = 5
css = "normal"

[buildPlans.AcuranzoMonoMail.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.AcuranzoMonoMail.subset]
include.ranges = [
  [32, 126],   # Basic ASCII printable
  [160, 255],  # Latin-1 Supplement
]
